### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by sweetstyle11** [sweetstyle11/02-29-pair-project#3]
- Create database schema.

  -User's Table
- [x] User name                         
- [x] User email
- [x] Phone Number
- [x] Password
- [x] User photo?

  - Contacts table
- [x]  Contact Name
- [x] Contact's Email
- [x] Mailing Address
- [x] Contact s' Phone number
- [x] Contact's Birthday
- [x] Preferred method of contact.  (id)
- [x] user_id

  - Completed Meetup (the actual event)
- [x] User id
- [x] Contact id 
- [x] Date of contact
- [x] Actual contact method (id)
- [x] Notes: (brief description of meetup/ phone call/ letter etc.) 

  - Methods of contact
- [x] Phone
- [x]  In person
- [x] Video call

**Comment by halfghaninne** [comment]
How is a contact connected to a user? For example, with this current schema, could a user view a list of all of their contacts, regardless of if they've met with them?

**Comment by youcatastrophe** [comment]
Thanks for the reminder, Alex. We assumed we'd be adding a user_id to the contacts table, as we definitely *do not* want just anybody to see the contact info. We just forgot to include this in our issues.

**Comment by halfghaninne** [comment]
Nice.

**Comment by youcatastrophe** [comment]
Link to Database spreadsheets in Google Docs: 
https://docs.google.com/spreadsheets/d/1t-hzmiVf7J1BikipHP_lW_YyLsiGk9WKRR6q2W2-uyk/edit?usp=sharing
